source 'https://rubygems.org'
ruby '2.0.0'

gem 'bourbon'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'neat'
gem 'pg'
gem 'quiet_assets'
gem 'rails', '4.0.1'
gem 'sass-rails', '~> 4.0.0'
gem 'simple_form'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'pry-rails', '~> 0.3.2'
end

group :development do
  gem 'guard-rspec', '~> 4.2.7'
  gem 'guard-spork', '~> 1.5.1'
  gem 'rb-fsevent', '~> 0.9.4'
  gem 'spork-rails', github: 'sporkrb/spork-rails'
end

group :test do
  gem 'database_cleaner', '~> 1.2.0'
  gem 'factory_girl', '~> 4.4.0'
  gem 'rspec-rails', '~> 2.14.1'
end
