source 'https://rubygems.org'
ruby '2.0.0'

gem 'bourbon'
gem 'jbuilder'
gem 'jquery-rails'
gem 'neat'
gem 'pg'
gem 'pry-debugger'
gem 'pry-rails'
gem 'quiet_assets'
gem 'rails', '4.1.0'
gem 'sass-rails'
gem 'simple_form'
gem 'turbolinks'
gem 'uglifier'

group :development, :test do
  gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'rb-fsevent' if `uname` =~ /Darwin/
  gem 'spring'
  gem 'spring-commands-rspec'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'simplecov'
end
